Tensor Initialization

TensorFlow provides convenient functions to initialize tensors with specific values or patterns.



Immutable: Tensors are immutable – you can't change their values once created.

Data types: float32, int32, bool, string, etc.

TensorFlow automatically picks the appropriate dtype unless specified.

In [8]:
pip install tensorflow


In [9]:
import tensorflow as tf
print(tf.__version__)


2.18.0


🔹 Using tf.zeros()

In [18]:
zeros_tensor = tf.zeros(shape=(2, 3))
print("Zeros Tensor:\n", zeros_tensor)


Zeros Tensor:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


🔹 Using tf.ones()

In [19]:
ones_tensor = tf.ones(shape=(3, 2), dtype=tf.float32)
print("Ones Tensor:\n", ones_tensor)


Ones Tensor:
 tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


🔹 Using tf.fill()

In [20]:
fill_tensor = tf.fill(dims=(2, 2), value=7)
print("Filled Tensor with 7:\n", fill_tensor)


Filled Tensor with 7:
 tf.Tensor(
[[7 7]
 [7 7]], shape=(2, 2), dtype=int32)


🔹 Using tf.eye()


In [21]:
identity_tensor = tf.eye(num_rows=3)
print("Identity Matrix:\n", identity_tensor)


Identity Matrix:
 tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


🔹 Using tf.random.uniform()


In [22]:
uniform_tensor = tf.random.uniform(shape=(3, 3), minval=0, maxval=10, dtype=tf.int32)
print("Uniform Random Tensor:\n", uniform_tensor)


Uniform Random Tensor:
 tf.Tensor(
[[3 0 0]
 [5 8 6]
 [6 7 9]], shape=(3, 3), dtype=int32)


🔹 Using tf.random.normal()


In [23]:
normal_tensor = tf.random.normal(shape=(2, 3), mean=0.0, stddev=1.0)
print("Normal Random Tensor:\n", normal_tensor)


Normal Random Tensor:
 tf.Tensor(
[[ 0.26243776  1.2721373  -0.14437445]
 [ 0.7142779   1.3713346  -0.5449332 ]], shape=(2, 3), dtype=float32)


Tensor Casting

🔹 Using tf.cast()



In [24]:
float_tensor = tf.constant([1.5, 2.3, 3.7], dtype=tf.float32)
int_tensor = tf.cast(float_tensor, dtype=tf.int32)
print("Original float tensor:", float_tensor)
print("Casted to int tensor:", int_tensor)


Original float tensor: tf.Tensor([1.5 2.3 3.7], shape=(3,), dtype=float32)
Casted to int tensor: tf.Tensor([1 2 3], shape=(3,), dtype=int32)


🔹 Boolean Casting Example



In [25]:
bool_tensor = tf.cast([0, 1, 2], tf.bool)
print("Boolean tensor:", bool_tensor)  # [False, True, True]


Boolean tensor: tf.Tensor([False  True  True], shape=(3,), dtype=bool)


Why Casting Matters:

Casting helps in type compatibility between tensors.

Crucial in model building when input/output types must match expected types.



In [26]:
# Challenge: Create a 4x4 identity matrix, multiply it by 5.5, then cast to int
matrix = tf.eye(4) * 5.5
matrix_int = tf.cast(matrix, dtype=tf.int32)
print("Original Matrix:\n", matrix)
print("Casted to int:\n", matrix_int)


Original Matrix:
 tf.Tensor(
[[5.5 0.  0.  0. ]
 [0.  5.5 0.  0. ]
 [0.  0.  5.5 0. ]
 [0.  0.  0.  5.5]], shape=(4, 4), dtype=float32)
Casted to int:
 tf.Tensor(
[[5 0 0 0]
 [0 5 0 0]
 [0 0 5 0]
 [0 0 0 5]], shape=(4, 4), dtype=int32)
