Math Operations with Tensors

Element-wise operations

Broadcasting

Aggregation

Comparison

Tensor-wise mathematical functions

These operations are foundational for building and training models, where tensors undergo transformations, normalizations, and computations like matrix multiplication, loss calculations, etc.



📌 Why Linear Algebra?
Neural networks rely heavily on matrix operations. Every layer, activation, and weight update internally uses matrix math:

Inputs are vectors

Weights are matrices

Outputs are matrix products

Understanding this is key to debugging and designing efficient models.



🔢 1. Dot Product (Scalar Product)
Definition: For two vectors of the same length, the dot product is the sum of products of corresponding elements.

Formula:
If
a = [a1, a2]
b = [b1, b2]
then
dot(a, b) = a1*b1 + a2*b2

In [2]:
pip install tensorflow


In [3]:
import tensorflow as tf
print(tf.__version__)


2.18.0


In [4]:
a = tf.constant([2, 3])
b = tf.constant([4, 5])
dot_result = tf.tensordot(a, b, axes=1)  # Scalar output
print("Dot Product:", dot_result.numpy())  # Output: 2*4 + 3*5 = 8 + 15 = 23


Dot Product: 23


🧮 2. Matrix Multiplication (matmul)


Unlike element-wise multiplication, tf.matmul follows matrix multiplication rules:

(m x n) * (n x p) = (m x p)



In [5]:
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])
C = tf.matmul(A, B)
print("Matrix Multiplication:\n", C.numpy())


Matrix Multiplication:
 [[19 22]
 [43 50]]


🧠 Question Tip: What’s the difference between tf.matmul() and tf.multiply()?

matmul: real matrix multiplication

multiply: element-wise



🔁 3. Transpose of a Matrix


Interchange of rows and columns.




In [6]:
A = tf.constant([[1, 2], [3, 4]])
print("Transpose:\n", tf.transpose(A).numpy())


Transpose:
 [[1 3]
 [2 4]]


🔄 4. Matrix Inverse


Only square matrices with non-zero determinants have an inverse.




In [7]:
A = tf.constant([[4., 7.], [2., 6.]])
inv_A = tf.linalg.inv(A)
print("Inverse:\n", inv_A.numpy())


Inverse:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


🧩 5. Matrix Determinant


Gives information like whether the matrix is invertible.


In [8]:
det = tf.linalg.det(A)
print("Determinant:", det.numpy())


Determinant: 10.0


🧱 6. Identity and Diagonal Matrices



In [9]:
identity = tf.eye(3)
print("3x3 Identity Matrix:\n", identity.numpy())

diag = tf.linalg.diag([1, 2, 3])
print("Diagonal Matrix:\n", diag.numpy())


3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Diagonal Matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


🧮 7. Solving Linear Systems


To solve Ax = b, use:



In [10]:
A = tf.constant([[3., 1.], [1., 2.]])
b = tf.constant([[9.], [8.]])
x = tf.linalg.solve(A, b)
print("Solution x:\n", x.numpy())


Solution x:
 [[2.]
 [3.]]


This is used in training to find optimal weights (minimizing loss often involves solving systems).

In [11]:
import tensorflow as tf

# Vectors
a = tf.constant([2, 3])
b = tf.constant([4, 5])
print("Dot Product:", tf.tensordot(a, b, axes=1).numpy())

# Matrices
A = tf.constant([[1., 2.], [3., 4.]])
B = tf.constant([[5., 6.], [7., 8.]])
print("Matrix Multiplication:\n", tf.matmul(A, B).numpy())

# Transpose
print("Transpose of A:\n", tf.transpose(A).numpy())

# Inverse
A_inv = tf.linalg.inv(tf.constant([[4., 7.], [2., 6.]]))
print("Inverse of A:\n", A_inv.numpy())

# Determinant
print("Determinant of A:", tf.linalg.det(A).numpy())

# Identity
print("Identity Matrix:\n", tf.eye(3).numpy())

# Diagonal
print("Diagonal Matrix:\n", tf.linalg.diag([1, 2, 3]).numpy())

# Solving linear system
A_sys = tf.constant([[3., 1.], [1., 2.]])
b_sys = tf.constant([[9.], [8.]])
solution = tf.linalg.solve(A_sys, b_sys)
print("Solution of Ax=b:\n", solution.numpy())


Dot Product: 23
Matrix Multiplication:
 [[19. 22.]
 [43. 50.]]
Transpose of A:
 [[1. 3.]
 [2. 4.]]
Inverse of A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Determinant of A: -2.0
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Diagonal Matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
Solution of Ax=b:
 [[2.]
 [3.]]
