What is a Tensor?

A tensor is a generalization of scalars, vectors, and matrices to potentially higher dimensions. In TensorFlow, tensors are the primary data structure used to represent all data, similar to NumPy arrays.

Immutable: Tensors are immutable – you can't change their values once created.

Data types: float32, int32, bool, string, etc.

TensorFlow automatically picks the appropriate dtype unless specified.

In [8]:
pip install tensorflow


In [9]:
import tensorflow as tf
print(tf.__version__)


2.18.0


Creating Tensors

🔹 Scalar Tensor (Rank-0)



In [10]:
scalar = tf.constant(5)
print("Scalar Tensor:", scalar)
print("Shape:", scalar.shape)
print("Rank (ndim):", scalar.ndim)
print("Data type:", scalar.dtype)


Scalar Tensor: tf.Tensor(5, shape=(), dtype=int32)
Shape: ()
Rank (ndim): 0
Data type: <dtype: 'int32'>


🔹 Vector Tensor (Rank-1)




In [11]:
vector = tf.constant([10.5, 20.3, 30.1])
print("\nVector Tensor:", vector)
print("Shape:", vector.shape)
print("Rank:", vector.ndim)



Vector Tensor: tf.Tensor([10.5 20.3 30.1], shape=(3,), dtype=float32)
Shape: (3,)
Rank: 1


🔹 Matrix Tensor (Rank-2)



In [12]:
matrix = tf.constant([[1, 2], [3, 4]])
print("\nMatrix Tensor:\n", matrix)
print("Shape:", matrix.shape)
print("Rank:", matrix.ndim)



Matrix Tensor:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Shape: (2, 2)
Rank: 2


🔹 3D Tensor (Rank-3)

In [13]:
tensor3d = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("\n3D Tensor:\n", tensor3d)
print("Shape:", tensor3d.shape)
print("Rank:", tensor3d.ndim)



3D Tensor:
 tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
Shape: (2, 2, 2)
Rank: 3


Check Tensor Attributes


In [14]:
print("DType of tensor3d:", tensor3d.dtype)
print("Size of tensor3d:", tf.size(tensor3d).numpy())  # Total elements
print("Number of dimensions:", tf.rank(tensor3d).numpy())  # Tensor rank


DType of tensor3d: <dtype: 'int32'>
Size of tensor3d: 8
Number of dimensions: 3


Custom DType Example

In [15]:
tensor_str = tf.constant(["Hello", "World"], dtype=tf.string)
print("\nString Tensor:", tensor_str)



String Tensor: tf.Tensor([b'Hello' b'World'], shape=(2,), dtype=string)


In [16]:
tensor_bool = tf.constant([True, False])
print("Boolean Tensor:", tensor_bool)


Boolean Tensor: tf.Tensor([ True False], shape=(2,), dtype=bool)


In [17]:
# Challenge: Create a 4x4 matrix with float values from 1 to 16
tensor = tf.constant([[float(i + j*4 + 1) for i in range(4)] for j in range(4)])
print("4x4 Matrix:\n", tensor)
print("Shape:", tensor.shape)


4x4 Matrix:
 tf.Tensor(
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]], shape=(4, 4), dtype=float32)
Shape: (4, 4)
